# Generated by Django 5.2.7 on 2025-10-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.CharField(max_length=20, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20, verbose_name='Студенческий билет'),
        ),
        migrations.CreateModel(
            name='RealSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20, verbose_name='Группа')),
                ('day', models.CharField(max_length=20, verbose_name='День недели')),
                ('time_start', models.CharField(blank=True, max_length=10, verbose_name='Начало')),
                ('time_end', models.CharField(blank=True, max_length=10, verbose_name='Конец')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('lesson_type', models.CharField(max_length=50, verbose_name='Тип занятия')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Преподаватель')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Аудитория')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'ordering': ['group', 'day', 'time_start'],
                'unique_together': {('group', 'day', 'time', 'subject')},
            },
        ),
    ]
