# Generated by Django 5.2.7 on 2025-10-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_studentprofile_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='realschedule',
            unique_together={('group', 'day', 'time_start', 'subject')},
        ),
        migrations.AddField(
            model_name='realschedule',
            name='week_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип недели'),
        ),
        migrations.AlterField(
            model_name='realschedule',
            name='time_end',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='realschedule',
            name='time_start',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.CharField(blank=True, max_length=20, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Студенческий билет'),
        ),
        migrations.RemoveField(
            model_name='realschedule',
            name='time',
        ),
    ]
