# Generated by Django 5.2.7 on 2025-10-27 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_realschedule_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Учебный год')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('student', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='RecordBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('экзамен', 'Экзамен'), ('зачёт', 'Зачёт'), ('дифференцированный зачёт', 'Дифференцированный зачёт'), ('курсовая работа', 'Курсовая работа')], max_length=50, verbose_name='Вид контроля')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('passed', models.BooleanField(default=False, verbose_name='Сдано')),
                ('date', models.DateField(verbose_name='Дата сдачи')),
                ('teacher', models.CharField(max_length=100, verbose_name='Преподаватель')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Дисциплина')),
                ('record_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.recordbook')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
